name: build-hugo-deploy-gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      
      - name: install tools
        run: sudo apt-get install jq

      - name: clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: install Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -6}_Linux-64bit.tar.gz | tar -xvzf-
          sudo mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/

      - name: build site
        run: hugo -d docs/
      
      - name: shrink-images
        run: find docs/ \(-name '*.png' -o -name '*.jpg' -o -name '*.jpeg'\) -print0 | xargs -0 -P8 -n2 mogrify -strip -thumbnail '1000>'

      - name: deploy site
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
